CREATE DATABASE IF NOT EXISTS seckill_auth DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE seckill_auth;
CREATE TABLE IF NOT EXISTS users (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,email VARCHAR(100) NOT NULL,password VARCHAR(255) NOT NULL,
 username VARCHAR(50) NOT NULL,phone VARCHAR(20),avatar VARCHAR(500),role TINYINT NOT NULL DEFAULT 0,
 status TINYINT NOT NULL DEFAULT 1,email_verified TINYINT(1) NOT NULL DEFAULT 0,token_version INT UNSIGNED NOT NULL DEFAULT 0,
 password_changed_at DATETIME,last_login_at DATETIME,last_login_ip VARCHAR(45),created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,deleted_at DATETIME,
 UNIQUE KEY uk_users_email(email),KEY idx_users_status_role(status,role)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
